### ISSUE TITLE
Server.js is missing

### ISSUE THREAD

**Issue by rishabhtimes** [codebusking/react-pwa-guide-kit#9]
server.js is missing so that ssr with PWA and server routing is not available, please help about this

**Comment by ragingwind** [comment]
Thanks for reporting. Unfortunately, SSR features has been removed https://github.com/codebusking/react-pwa-guide-kit/commit/ab0fd794ba547a8af16a4b7791d6c1577ffb5fa0

But I recognized that remain information about server.js I will update package.json and readme
